apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mogah.vincent@hotmail.com
    privateKeySecretRef:
      name: acme-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
